version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:80"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - hasura
      - postgres

  hasura:
    build:
      context: ./hasura
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/mydb
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    depends_on:
      - postgres

  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
